### ISSUE TITLE
rename .moneywellspentrc

### ISSUE THREAD

**Issue by Wayneoween** [Flowm/MoneyWellSpent#2]
Just an idea:

rename `.moneywellspentrc` to `.moneywellspentrc.sample` and add `.moneywellspentrc` to the `.gitignore` so that one could not accidentally push his login credentials in his forked repository.

**Comment by Wayneoween** [comment]
Oh, long time no use. Has to be copied in the home anyway. Sorry for the noise.

**Comment by Flowm** [comment]
Yea, accidentally pushing the login credentials shouldn't be an issue, but highlighting that the config needs to be moved still makes sense. Thanks!
