### ISSUE TITLE
xpath of order list on logged-in landing page has changed (probably)

### ISSUE THREAD

**Issue by Wayneoween** [Flowm/MoneyWellSpent#3]
Currently `moneywellspent` is not functional, most likely due to the new design on https://www.amazon.de/gp/css/homepage.html/ref=nav_youraccount_btn :cry: 

Wouldn't it be possible to go to https://www.amazon.de/gp/your-account/order-history?ref_=ya_d_c_yo after logging in? Probably not, otherwise this would have been the way from the start I guess.

Will investigate in time, but just wanted to let you know!

Thanks for your effort! :heart:

**Comment by Flowm** [comment]
Still seems to be working fine for me.

Unfortunately no debug output was printed when an error occurs during that stage.
With commit 269537374274cf9b33ab14ffabf1aef9c6857451 the script now dumps the complete page to the console when the `-d` debug option is set.

As posting the complete page here probably is a bad idea, searching the output for the xpaths referenced in the script might be a viable option. Hope that helps.

**Comment by Wayneoween** [comment]
Okay, awesome!

**Comment by Wayneoween** [comment]
This seems acutally to be another issue. Not necessarily the xpath but something with the website and/or `mechanize`.

```
marius at pewpew in ~/code/gh/MoneyWellSpent on master*
$ ./moneywellspent.rb -o -y 2017 -q
/home/marius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/form.rb:217:in `method_missing': undefined method `password=' for #<Mechanize::Form:0x0056549bff02f8> (NoMethodError)
	from ./moneywellspent.rb:41:in `run'
	from ./moneywellspent.rb:258:in `<main>'
marius at pewpew in ~/code/gh/MoneyWellSpent on master*
$ ./moneywellspent.rb -o -y 2017 -q
/home/marius/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/form.rb:217:in `method_missing': undefined method `password=' for #<Mechanize::Form:0x0055c4d251cbf0> (NoMethodError)
	from ./moneywellspent.rb:41:in `run'
	from ./moneywellspent.rb:258:in `<main>'
marius at pewpew in ~/code/gh/MoneyWellSpent on master*
$ ./moneywellspent.rb -o -y 2017 -q
Overall 2017:   1728.30
```
Ran 3 times, two times there was no `password` field in the form apparently. 
Probably worth to open another issue for that, right?

(I implemented `-o` to just print the sum, will make a PR for that)

**Comment by Flowm** [comment]
Did you have any luck in getting the debug output while the error was occurring?

**Comment by Wayneoween** [comment]
Yes, and if I look at what would get rendered I see what the problem seems to be as well ([HTML](http://ix.io/Cdg)):

![screenshot-2017-11-13 amazon anmelden](https://user-images.githubusercontent.com/630640/32734659-ee4de7ce-c892-11e7-855a-30ec6b6dfc38.png)


While a successfull attempt looks like this ([HTML](http://ix.io/Cdh)):

![screenshot-2017-11-13 amazon anmelden 1](https://user-images.githubusercontent.com/630640/32734955-bebb9172-c893-11e7-81a4-91016a4dd509.png)

**Comment by Flowm** [comment]
Thanks for finding the issue. Should not be too hard to detect the different sites, I'll have a look soon.
